spring.application.name=notification-service
server.port=8083
management.endpoints.web.exposure.include=health,info

spring.cloud.aws.region.static=${AWS_REGION:us-east-2}

app.queues.notification=${NOTIFICATION_QUEUE:payment-notification}