spring.datasource.url=jdbc:tc:sqlserver:2022-CU14-ubuntu-22.04:///payment_orchestrator?TC_ACCEPT_LICENSE=true
spring.datasource.username=test
spring.datasource.password=test
spring.flyway.enabled=true
app.security.enabled=false
