spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}
spring.cloud.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}
app.security.enabled=false
management.datadog.metrics.export.enabled=false
