app.security.enabled=true

spring.security.oauth2.client.registration.cognito.client-id=${COGNITO_CLIENT_ID:""}
spring.security.oauth2.client.registration.cognito.client-secret=${COGNITO_CLIENT_SECRET:""}
spring.security.oauth2.client.registration.cognito.scope=phone,openid,email
spring.security.oauth2.client.registration.cognito.redirect-uri=${COGNITO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/cognito}
spring.security.oauth2.client.provider.cognito.issuer-uri=${COGNITO_ISSUER_URI:https://cognito-idp.us-east-2.amazonaws.com/us-east-2_61TReCB6N}
spring.security.oauth2.client.provider.cognito.user-name-attribute=username
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI:https://cognito-idp.us-east-2.amazonaws.com/us-east-2_61TReCB6N}

app.security.cognito.domain=${COGNITO_DOMAIN:https://us-east-261trecb6n.auth.us-east-2.amazoncognito.com}
app.security.cognito.logout-redirect-uri=${COGNITO_LOGOUT_REDIRECT_URI:http://localhost:8080}
