spring.datasource.url=jdbc:postgresql://localhost:5432/payment_orchestrator
spring.datasource.username=payment_user
spring.datasource.password=payment_pass
spring.cloud.aws.endpoint=http://localhost:4566
app.security.enabled=false
management.datadog.metrics.export.enabled=false
