spring.application.name=payment-service
spring.datasource.url=${AWS_SQLSERVER_JDBC_URL:""}
spring.datasource.username=${AWS_SQLSERVER_USERNAME:""}
spring.datasource.password=${AWS_SQLSERVER_PASSWORD:""}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/{vendor}

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0
management.datadog.metrics.export.enabled=false

spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:""}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:""}

app.queues.payment-created=${PAYMENT_CREATED_QUEUE:""}
app.outbox.publisher-delay-ms=3000
app.security.enabled=${APP_SECURITY_ENABLED:false}
