spring.application.name=settlement-service
server.port=8082
management.endpoints.web.exposure.include=health,info

# DataSource — SQL Server RDS (mesma instância do payment-service)
spring.datasource.url=${AWS_SQLSERVER_JDBC_URL}
spring.datasource.username=${AWS_SQLSERVER_USERNAME:admin}
spring.datasource.password=${AWS_SQLSERVER_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.data-source-properties.encrypt=true
spring.datasource.hikari.data-source-properties.trustServerCertificate=true

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/sqlserver
spring.flyway.table=settlement_schema_history
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# AWS
spring.cloud.aws.region.static=${AWS_REGION:us-east-2}

app.queues.settlement=${SETTLEMENT_QUEUE:payment-settlement}
