spring.application.name=settlement-service
server.port=8082
management.endpoints.web.exposure.include=health,info

spring.cloud.aws.region.static=${AWS_REGION:us-east-2}
app.queues.settlement=${SETTLEMENT_QUEUE:payment-settlement}