sonar.projectKey=pj-payment-orchestrator-backend
sonar.projectName=pj-payment-orchestrator-backend
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.exclusions=**/config/**,**/*Application.java
